language: python

python:
  - "2.7"

# command to install dependencies
install:
  - pip install tox
  # Temporal solution to travis issue #155
  - sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm

# command to run tests
script: tox
